CREATE TABLE "GCG_5800_PO_CONF"(
 "PURCHASE_ORDER" CHAR(7),
 "PO_LINE" CHAR(3),
 "CONF" CHAR(1),
 "GS_USER" CHAR(8),
 "DATE_CONF" DATE,
 "COLUMN0" CHAR(7),
 "COLUMN1" CHAR(1),
 "COLUMN2" CHAR(8),
 "COLUMN3" DATE);

CREATE INDEX "GCG_5800_PO_CONF00" USING 0 ON "GCG_5800_PO_CONF"("PURCHASE_ORDER", "PO_LINE");